# Kubernetes Secrets Configuration v1
# Enhanced security controls with automated rotation and audit capabilities
# Requires Kubernetes v1.21+ for immutable secrets support
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: event-simulator
  labels:
    security-tier: high
    rotation-required: "true"
  annotations:
    rotation-schedule: "90-days"
    last-rotated: "timestamp"
    secret-owner: "database-admin"
    kubectl.kubernetes.io/last-applied-configuration: ""
data:
  sql-username: base64_encoded_username
  sql-password: base64_encoded_password
  connection-string: base64_encoded_connection_string
type: Opaque
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: template-service-secrets
  namespace: event-simulator
  labels:
    security-tier: high
    encryption-keys: "true"
  annotations:
    key-rotation-schedule: "30-days"
    last-rotated: "timestamp"
    encryption-standard: "AES-256"
    kubectl.kubernetes.io/last-applied-configuration: ""
data:
  storage-key: base64_encoded_storage_key
  encryption-key: base64_encoded_encryption_key
  api-key: base64_encoded_api_key
type: Opaque
immutable: true
---
# RBAC Configuration for Secret Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-generator-role
  namespace: event-simulator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["database-credentials"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: template-service-role
  namespace: event-simulator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["template-service-secrets"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-generator-sa
  namespace: event-simulator
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-service-sa
  namespace: event-simulator
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-generator-rolebinding
  namespace: event-simulator
subjects:
- kind: ServiceAccount
  name: event-generator-sa
  namespace: event-simulator
roleRef:
  kind: Role
  name: event-generator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: template-service-rolebinding
  namespace: event-simulator
subjects:
- kind: ServiceAccount
  name: template-service-sa
  namespace: event-simulator
roleRef:
  kind: Role
  name: template-service-role
  apiGroup: rbac.authorization.k8s.io